services:
  bitcoinwebapp:
    container_name: bitcoinwebapp
    build: 
      context: ./app
      dockerfile: ../Dockerfile
    ports:
      - "9000:3333"
    volumes:
      - ./app:/home/docker/app
    tty: true
    restart: always
